# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
logo: /assets/images/logo.png
title: yodiwo
email: info@yodiwo.com
description: > # this means to ignore newlines until "baseurl:"
  The leading IoT Application enablement for Enterprises.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.yodiwo.com" # the base hostname & protocol for your site
twitter_username: yodiwo_iot
github_username:  yodiwo

# Build settings
markdown: kramdown
